"""
generate_evidence_cards.py — Step 9: Evidence card generator for NeuroGraph Agent.

Generates structured, cautious research briefs for each of the 499 scored targets.
All content is derived from existing pipeline outputs. No LLMs, no external APIs.

Run with:
    python -m src.processing.generate_evidence_cards
"""

from __future__ import annotations

import re
import textwrap
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

# ── Paths ─────────────────────────────────────────────────────────────────────
ROOT         = Path(__file__).resolve().parents[2]
DATA         = ROOT / "Data" / "processed"
EVIDENCE_DIR = ROOT / "outputs" / "evidence_cards"
FIGURES_DIR  = ROOT / "outputs" / "figures"
REPORTS_DIR  = ROOT / "outputs" / "reports"

EVIDENCE_DIR.mkdir(parents=True, exist_ok=True)
FIGURES_DIR.mkdir(parents=True, exist_ok=True)
REPORTS_DIR.mkdir(parents=True, exist_ok=True)

# ── Constants ─────────────────────────────────────────────────────────────────
COMPARATOR_SYMS = {"APP", "APOE", "PSEN1", "PSEN2", "MAPT", "CLU", "BIN1"}
MAX_TABLE_ROWS  = 5
MAX_TITLE_LEN   = 110

DISCLAIMER = (
    "> **Disclaimer:** This card is generated from computational analysis of a "
    "retrieved corpus sample.\n"
    "> It is hypothesis-generating only and **not clinical decision support**.\n"
    "> All findings require expert biomedical validation before informing any decision."
)

FOOTER = (
    "*Generated by NeuroGraph Agent — Step 9: Evidence Card Generator.*  \n"
    "*Source: computational analysis of 478 papers and ~1,000 clinical trial registrations.*  \n"
    "***Not clinical decision support.***"
)

LIMITATIONS_UNIVERSAL = [
    "Lexical symbol matching may miss aliases, synonyms, and protein/drug names.",
    "Short or common symbols may produce false positives in non-biological text contexts.",
    "The literature corpus covers a sample (~478 papers); zero mentions ≠ zero coverage overall.",
    "Trial text may name drugs or interventions rather than molecular targets; low trial signal "
    "does not prove absence of relevant trials.",
    "Open Targets association scores reflect multi-source research evidence, not therapeutic viability.",
    "NMF topic labels are statistically derived approximations, not curated clinical categories.",
    "This card is not clinical decision support and must not inform clinical or drug-development decisions.",
]

NEXT_STEPS_UNIVERSAL = [
    "Manually inspect matched papers/trials to confirm symbol relevance.",
    "Search using aliases, protein names, and drug names (not only gene symbol).",
    "Validate target biology using curated domain literature and pathway databases.",
    "Check whether relevant drug programmes exist under intervention names rather than target symbol.",
    "Compare against Open Targets full evidence category breakdown (genetics, literature, CRISPR, etc.).",
    "Consider PubTator, UniProt, STRING, or Reactome for mechanistic context.",
    "Expert biomedical review is required before drawing any research or development conclusions.",
]


# ── Data loading ──────────────────────────────────────────────────────────────

def _load_csv(path: Path, label: str) -> pd.DataFrame | None:
    if path.exists():
        return pd.read_csv(path, low_memory=False)
    print(f"  [WARNING] Not found: {path.name} ({label})")
    return None


def _safe(value, default: str = "—") -> str:
    if value is None or (isinstance(value, float) and np.isnan(value)):
        return default
    return str(value).strip() or default


def _shorten(text: str, max_len: int = MAX_TITLE_LEN) -> str:
    t = str(text).strip()
    return t if len(t) <= max_len else t[:max_len - 1] + "…"


# ── Signal classifiers ────────────────────────────────────────────────────────

def classify_evidence_strength(score: float) -> str:
    if pd.isna(score):
        return "Unknown evidence signal"
    if score >= 0.70:
        return "High evidence signal"
    if score >= 0.50:
        return "Moderate evidence signal"
    return "Lower evidence signal"


def classify_literature_signal(mentions: int) -> str:
    if pd.isna(mentions) or mentions == 0:
        return "No detected literature signal"
    if mentions >= 10:
        return "Strong literature signal"
    if mentions >= 3:
        return "Moderate literature signal"
    return "Weak literature signal"


def classify_trial_signal(mentions: int) -> str:
    if pd.isna(mentions) or mentions == 0:
        return "No detected trial text signal"
    if mentions >= 10:
        return "High trial text signal"
    if mentions >= 2:
        return "Moderate trial text signal"
    return "Low trial text signal"


# ── Evidence retrieval helpers ────────────────────────────────────────────────

def get_matched_papers(
    sym: str,
    kg_edges: pd.DataFrame,
    lit_assign: pd.DataFrame,
    lit_clean: pd.DataFrame | None,
) -> pd.DataFrame:
    """Return papers matched to sym via knowledge graph edges."""
    if kg_edges is None or lit_assign is None:
        return pd.DataFrame()
    p_edges = kg_edges[
        (kg_edges["edge_type"] == "target_mentioned_in_paper")
        & (kg_edges["target_symbol"] == sym)
    ]
    if len(p_edges) == 0:
        return pd.DataFrame()
    pids = p_edges["paper_id"].dropna().astype(str).tolist()
    matched = lit_assign[lit_assign["paper_id"].astype(str).isin(pids)].copy()
    if lit_clean is not None and "venue" in lit_clean.columns:
        venue_map = (
            lit_clean[["paper_id", "venue"]]
            .astype({"paper_id": str})
            .drop_duplicates("paper_id")
        )
        matched = matched.merge(venue_map, on="paper_id", how="left")
    return matched.sort_values("citation_count", ascending=False).reset_index(drop=True)


def get_matched_trials(
    sym: str,
    kg_edges: pd.DataFrame,
    trial_assign: pd.DataFrame,
) -> pd.DataFrame:
    """Return trials matched to sym via knowledge graph edges."""
    if kg_edges is None or trial_assign is None:
        return pd.DataFrame()
    t_edges = kg_edges[
        (kg_edges["edge_type"] == "target_mentioned_in_trial")
        & (kg_edges["target_symbol"] == sym)
    ]
    if len(t_edges) == 0:
        return pd.DataFrame()
    tids = t_edges["nct_id"].dropna().astype(str).tolist()
    matched = trial_assign[trial_assign["nct_id"].astype(str).isin(tids)].copy()
    return matched.reset_index(drop=True)


def infer_dominant_theme(df: pd.DataFrame, col: str = "topic_label") -> str:
    """Return the most common topic label in df[col], or '—'."""
    if df is None or len(df) == 0 or col not in df.columns:
        return "—"
    counts = df[col].dropna().value_counts()
    if len(counts) == 0:
        return "—"
    top = counts.head(2).index.tolist()
    return "; ".join(top)


# ── Narrative generators ──────────────────────────────────────────────────────

def generate_why_interesting(row: pd.Series) -> str:
    tier  = _safe(row.get("gap_interpretation_tier"))
    flag  = _safe(row.get("symbol_ambiguity_flag"), "low")
    sym   = _safe(row.get("approved_symbol"))

    if tier == "Strong text-supported gap signal":
        base = (
            f"{sym} combines a measurable literature signal with comparatively low clinical "
            "trial text signal in this corpus. This may suggest a research-to-translation "
            "gap — literature research appears to be ahead of registered trial activity based "
            "on lexical text matching. Manual validation is required to determine whether "
            "this reflects a genuine translational opportunity."
        )
    elif tier == "Established / trial-covered target":
        base = (
            f"{sym} appears well represented in both literature and trial text in this corpus. "
            "It should be treated as an established or trial-covered comparator rather than "
            "a gap candidate. It may serve as a reference point for comparing less-studied targets."
        )
    elif tier == "Checked-zero text signal":
        base = (
            f"{sym} has an Open Targets association score but no symbol detections were found "
            "in the retrieved literature or trial corpus. This may reflect alias-only coverage, "
            "trial registration by drug name rather than target symbol, or genuine absence from "
            "this corpus sample. It should be treated as a checked-zero lexical signal — "
            "not confirmed underexploration."
        )
    elif tier == "Low-priority / weak gap signal":
        base = (
            f"{sym} shows weak evidence and literature signals in this corpus. "
            "It may represent a lower-priority target relative to others in this dataset, "
            "but this assessment is limited to the retrieved corpus sample."
        )
    else:
        base = (
            f"{sym} requires manual review. Its tier classification was not standard "
            "in this pipeline run."
        )

    if flag in ("high", "moderate"):
        base += (
            f" Note: the symbol '{sym}' may be ambiguous in biomedical or general text; "
            "mention counts require manual validation to exclude false positives."
        )

    return base


def generate_limitations(row: pd.Series) -> list[str]:
    sym  = _safe(row.get("approved_symbol"))
    flag = _safe(row.get("symbol_ambiguity_flag"), "low")
    lims = list(LIMITATIONS_UNIVERSAL)
    if flag in ("high", "moderate"):
        lims.insert(0, f"Symbol '{sym}' has a {flag} ambiguity flag — mention counts are especially uncertain.")
    return lims


def generate_next_steps(row: pd.Series) -> list[str]:
    return list(NEXT_STEPS_UNIVERSAL)


# ── Markdown card writer ──────────────────────────────────────────────────────

def _md_table(df: pd.DataFrame, cols: list[str], rename: dict[str, str] | None = None) -> str:
    """Render a subset of df columns as a markdown table string."""
    sub_cols = [c for c in cols if c in df.columns]
    if not sub_cols:
        return ""
    tmp = df[sub_cols].copy().head(MAX_TABLE_ROWS)
    if rename:
        tmp = tmp.rename(columns=rename)
    header = " | ".join(str(c) for c in tmp.columns)
    sep    = " | ".join(["---"] * len(tmp.columns))
    rows   = []
    for _, r in tmp.iterrows():
        cells = []
        for c in tmp.columns:
            val = r[c]
            if pd.isna(val) or str(val).strip() in ("", "nan", "NaN"):
                cells.append("—")
            else:
                s = _shorten(str(val), 80)
                cells.append(s)
        rows.append(" | ".join(cells))
    return f"| {header} |\n| {sep} |\n" + "\n".join(f"| {r} |" for r in rows)


def write_markdown_card(
    row: pd.Series,
    papers: pd.DataFrame,
    trials: pd.DataFrame,
) -> str:
    sym  = _safe(row.get("approved_symbol"))
    name = _safe(row.get("approved_name"))
    tid  = _safe(row.get("target_id"))
    bio  = _safe(row.get("biotype"))
    tier = _safe(row.get("gap_interpretation_tier"))
    flag = _safe(row.get("symbol_ambiguity_flag"))

    assoc_score = row.get("association_score", 0.0)
    gap_score   = row.get("gap_score",         0.0)
    con_score   = row.get("conservative_gap_score", 0.0)
    gap_rank    = row.get("gap_rank",           "—")
    gap_cat     = _safe(row.get("gap_category"))
    lit_ment    = int(row.get("literature_mentions",          0) or 0)
    lit_docs    = int(row.get("literature_documents_mentioned", 0) or 0)
    tri_ment    = int(row.get("trial_mentions",               0) or 0)
    tri_docs    = int(row.get("trial_documents_mentioned",    0) or 0)

    ev_label  = classify_evidence_strength(assoc_score)
    lit_label = classify_literature_signal(lit_ment)
    tri_label = classify_trial_signal(tri_ment)

    dom_lit   = infer_dominant_theme(papers,  "topic_label")
    dom_trial = infer_dominant_theme(trials, "topic_label")

    why   = generate_why_interesting(row)
    lims  = generate_limitations(row)
    steps = generate_next_steps(row)

    lines: list[str] = []

    # ── Header ────────────────────────────────────────────────────────────────
    lines.append(f"# Target Evidence Card: {sym}\n")
    lines.append(DISCLAIMER)
    lines.append("\n---\n")

    # ── Section 1: Snapshot ───────────────────────────────────────────────────
    lines.append("## 1. Target Snapshot\n")
    snap = [
        ("Symbol",                  sym),
        ("Approved Name",           name),
        ("Target ID",               tid),
        ("Biotype",                 bio),
        ("Association Score",       f"{float(assoc_score):.4f}" if pd.notna(assoc_score) else "—"),
        ("Gap Score",               f"{float(gap_score):.4f}"   if pd.notna(gap_score)   else "—"),
        ("Conservative Gap Score",  f"{float(con_score):.4f}"   if pd.notna(con_score)   else "—"),
        ("Gap Rank",                str(int(gap_rank)) if pd.notna(gap_rank) else "—"),
        ("Gap Category",            gap_cat),
        ("Gap Interpretation Tier", tier),
        ("Symbol Ambiguity Flag",   flag),
    ]
    lines.append("| Field | Value |")
    lines.append("|---|---|")
    for k, v in snap:
        lines.append(f"| {k} | {v} |")
    lines.append("")

    # ── Section 2: Evidence Strength ──────────────────────────────────────────
    lines.append("## 2. Evidence Strength\n")
    lines.append(f"**{ev_label}** (association score: {float(assoc_score):.4f})\n")
    lines.append(
        "This reflects Open Targets association evidence in this dataset, "
        "not therapeutic validation. Higher scores indicate stronger multi-source "
        "research evidence linking this target to Alzheimer's disease in the Open Targets database."
    )
    lines.append("")

    # ── Section 3: Literature Signal ──────────────────────────────────────────
    lines.append("## 3. Literature Signal\n")
    lines.append(f"**{lit_label}**\n")
    lines.append(
        f"In this retrieved literature corpus, the target symbol was detected "
        f"{lit_ment} time(s) across {lit_docs} document(s)."
    )
    lines.append("")
    lines.append(
        "> Note: These counts reflect a corpus sample (~478 papers). "
        "Zero mentions does not mean zero coverage in the broader literature."
    )
    if dom_lit != "—":
        lines.append(f"\n**Dominant literature themes:** {dom_lit}")
    lines.append("")

    # ── Section 4: Clinical Trial Signal ──────────────────────────────────────
    lines.append("## 4. Clinical Trial Signal\n")
    lines.append(f"**{tri_label}**\n")
    lines.append(
        f"In this retrieved trial corpus, the target symbol was detected "
        f"{tri_ment} time(s) across {tri_docs} registration(s)."
    )
    lines.append("")
    lines.append(
        "> **Important:** Low trial text signal does not prove absence of relevant trials. "
        "Trial registrations typically name drugs or intervention classes rather than "
        "molecular target symbols."
    )
    if dom_trial != "—":
        lines.append(f"\n**Dominant trial themes:** {dom_trial}")
    lines.append("")

    # ── Section 5: Research Theme Context ─────────────────────────────────────
    lines.append("## 5. Research Theme Context\n")
    lines.append(
        "Themes are derived from NMF topic models applied to TF-IDF representations "
        "of literature abstracts and trial text. Labels are statistically derived "
        "approximations — they require expert interpretation."
    )
    lines.append("")
    lines.append(f"- **Dominant literature themes:** {dom_lit}")
    lines.append(f"- **Dominant trial themes:** {dom_trial}")
    if dom_lit != "—" and dom_trial != "—" and dom_lit == dom_trial:
        lines.append(
            "\nTheme overlap detected between literature and trial contexts — "
            "may indicate an active research and translation programme for this topic area."
        )
    elif dom_lit == "—" and dom_trial == "—":
        lines.append(
            "\nNo matched records found in this corpus — theme context cannot be inferred."
        )
    lines.append("")

    # ── Section 6: Why This Target Is Interesting ──────────────────────────────
    lines.append("## 6. Why This Target May Be Interesting\n")
    lines.append(why)
    lines.append("")

    # ── Section 7: Evidence Links ─────────────────────────────────────────────
    lines.append("## 7. Evidence Links / Supporting Records\n")

    lines.append("### Matched Papers (corpus sample)\n")
    if len(papers) > 0:
        paper_cols = ["title", "year", "citation_count", "venue", "topic_label"]
        paper_rename = {
            "title": "Title", "year": "Year",
            "citation_count": "Citations", "venue": "Venue", "topic_label": "Topic",
        }
        tbl = _md_table(papers, paper_cols, paper_rename)
        if tbl:
            lines.append(tbl)
            if len(papers) > MAX_TABLE_ROWS:
                lines.append(
                    f"\n*Showing top {MAX_TABLE_ROWS} of {len(papers)} matched papers "
                    "(ranked by citation count).*"
                )
    else:
        lines.append(
            "No direct symbol-matched records were found in this corpus sample. "
            "This does not mean the target is absent from the broader literature."
        )
    lines.append("")

    lines.append("### Matched Trials (corpus sample)\n")
    if len(trials) > 0:
        trial_cols = ["nct_id", "brief_title", "overall_status", "phases", "topic_label"]
        trial_rename = {
            "nct_id": "NCT ID", "brief_title": "Brief Title",
            "overall_status": "Status", "phases": "Phase", "topic_label": "Topic",
        }
        tbl = _md_table(trials, trial_cols, trial_rename)
        if tbl:
            lines.append(tbl)
            if len(trials) > MAX_TABLE_ROWS:
                lines.append(
                    f"\n*Showing top {MAX_TABLE_ROWS} of {len(trials)} matched trials.*"
                )
    else:
        lines.append(
            "No direct symbol-matched records were found in this corpus sample. "
            "This does not mean no relevant trials exist — trial text may describe "
            "interventions by drug name rather than molecular target symbol."
        )
    lines.append("")

    # ── Section 8: Limitations ────────────────────────────────────────────────
    lines.append("## 8. Limitations\n")
    for lim in lims:
        lines.append(f"- {lim}")
    lines.append("")

    # ── Section 9: Suggested Next Validation Steps ────────────────────────────
    lines.append("## 9. Suggested Next Validation Steps\n")
    for i, step in enumerate(steps, 1):
        lines.append(f"{i}. {step}")
    lines.append("")

    lines.append("---\n")
    lines.append(FOOTER)

    return "\n".join(lines)


# ── Figure generator ──────────────────────────────────────────────────────────

def plot_signal_profile(gap: pd.DataFrame, strong_syms: list[str]) -> None:
    """Grouped bar chart: literature vs trial mentions for strong candidates + comparators."""
    syms_to_show = list(strong_syms[:10]) + [
        s for s in COMPARATOR_SYMS if s in gap["approved_symbol"].values
        and s not in strong_syms[:10]
    ]
    sub = gap[gap["approved_symbol"].isin(syms_to_show)].copy()
    sub = sub.sort_values("gap_score", ascending=False).reset_index(drop=True)

    n = len(sub)
    x = np.arange(n)
    w = 0.38

    fig, ax = plt.subplots(figsize=(max(10, n * 0.9 + 1), 5))
    ax.bar(x - w / 2, sub["literature_mentions"], width=w,
           label="Literature mentions", color="#2176ae", alpha=0.88)
    ax.bar(x + w / 2, sub["trial_mentions"],      width=w,
           label="Trial text mentions", color="#e07b39", alpha=0.88)

    ax.set_xticks(x)
    ax.set_xticklabels(sub["approved_symbol"], rotation=40, ha="right", fontsize=9)
    ax.set_ylabel("Symbol mention count (this corpus)")
    ax.set_title(
        "Signal Profile: Literature vs Trial Mentions\n"
        "Strong gap candidates (blue label) and established comparators (grey label) — "
        "corpus sample only",
        fontsize=10,
    )
    ax.legend(framealpha=0.8, fontsize=9)

    # Colour x-tick labels: strong = blue, comparator = grey
    for tick_lbl, sym in zip(ax.get_xticklabels(), sub["approved_symbol"]):
        if sym in strong_syms:
            tick_lbl.set_color("#d62728")
        else:
            tick_lbl.set_color("#555555")

    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    fig.tight_layout()

    out_path = FIGURES_DIR / "cards_01_signal_profile_examples.png"
    fig.savefig(out_path, dpi=150, bbox_inches="tight")
    plt.close(fig)
    print(f"  [FIGURE] Saved {out_path.name}")


# ── Brief-pack renderer ───────────────────────────────────────────────────────

def build_brief_pack(
    gap: pd.DataFrame,
    kg_edges: pd.DataFrame,
    lit_assign: pd.DataFrame,
    lit_clean: pd.DataFrame | None,
    trial_assign: pd.DataFrame,
) -> str:
    """Return markdown string for the top-candidate brief pack."""
    strong_df = gap[
        gap["gap_interpretation_tier"] == "Strong text-supported gap signal"
    ].sort_values("gap_rank").reset_index(drop=True)

    comp_df = gap[
        (gap["gap_interpretation_tier"] == "Established / trial-covered target")
        & (gap["approved_symbol"].isin(COMPARATOR_SYMS))
    ].sort_values("gap_rank").reset_index(drop=True)

    lines = [
        "# NeuroGraph Agent — Top Gap Candidate Brief Pack\n",
        "> **Disclaimer:** Research intelligence prototype. Computationally derived, "
        "hypothesis-generating only.  \n"
        "> **Not clinical decision support.** All findings require expert biomedical validation.\n",
        "---\n",
        "## Part A: Strong Text-Supported Gap Candidates\n",
        "Targets with Open Targets evidence AND measurable literature signal AND "
        "low trial text signal in this corpus.\n",
        "---\n",
    ]

    for _, row in strong_df.iterrows():
        sym    = _safe(row["approved_symbol"])
        papers = get_matched_papers(sym, kg_edges, lit_assign, lit_clean)
        trials = get_matched_trials(sym, kg_edges, trial_assign)
        lines.append(write_markdown_card(row, papers, trials))
        lines.append("\n---\n")

    lines.append("## Part B: Established / Trial-Covered Comparators\n")
    lines.append(
        "These targets appear well represented in trial text. They serve as reference "
        "comparators for assessing how gap candidates compare against known active programmes.\n"
    )
    lines.append("---\n")

    for _, row in comp_df.iterrows():
        sym    = _safe(row["approved_symbol"])
        papers = get_matched_papers(sym, kg_edges, lit_assign, lit_clean)
        trials = get_matched_trials(sym, kg_edges, trial_assign)
        lines.append(write_markdown_card(row, papers, trials))
        lines.append("\n---\n")

    return "\n".join(lines)


# ── Validation checks ─────────────────────────────────────────────────────────

_FORBIDDEN = [
    "clinical decision support",
    "therapeutically valid",
    " proves ",
    "guaranteed",
    "proven to",
]


def validate_card(path: Path, sym: str) -> list[str]:
    errors = []
    text = path.read_text(encoding="utf-8").lower()
    for phrase in _FORBIDDEN:
        # "not clinical decision support" is fine; bare "clinical decision support" is not
        if phrase == "clinical decision support":
            # Allow if preceded by "not " or "no " or "isn't "
            hits = [m.start() for m in re.finditer(re.escape(phrase), text)]
            for h in hits:
                window = text[max(0, h - 10): h]
                if not any(neg in window for neg in ("not ", "no ", "isn't ", "n't ")):
                    errors.append(f"{sym}: forbidden phrase detected: '{phrase}'")
        else:
            if phrase in text:
                errors.append(f"{sym}: forbidden phrase detected: '{phrase}'")
    return errors


# ── Summary report ────────────────────────────────────────────────────────────

def write_summary_report(
    gap: pd.DataFrame,
    cards_df: pd.DataFrame,
    n_created: int,
    validation_errors: list[str],
) -> None:
    tier_counts = gap["gap_interpretation_tier"].value_counts()
    top10 = (
        cards_df.sort_values("gap_rank")
        .head(10)[["gap_rank", "approved_symbol", "gap_interpretation_tier",
                   "literature_signal_label", "trial_signal_label", "evidence_strength_label"]]
    )

    lines = [
        "# NeuroGraph Agent — Evidence Card Generation Summary\n",
        f"*Step 9: Evidence Card Generator*\n",
        "---\n",
        "## Overview\n",
        f"- **Total targets scored:** {len(gap)}",
        f"- **Evidence cards generated:** {n_created}",
        f"- **Markdown cards saved to:** `outputs/evidence_cards/`",
        f"- **Summary table saved to:** `Data/processed/target_evidence_cards.csv`",
        f"- **Top brief pack:** `outputs/reports/top_gap_candidate_briefs.md`",
        f"- **Signal profile figure:** `outputs/figures/cards_01_signal_profile_examples.png`",
        "",
        "---\n",
        "## Tier Distribution\n",
        "| Gap Interpretation Tier | Count |",
        "|---|---|",
    ]
    for tier, cnt in tier_counts.items():
        lines.append(f"| {tier} | {cnt} |")
    lines.append("")

    lines += [
        "---\n",
        "## Top 10 Targets by Gap Rank\n",
        "| Rank | Symbol | Tier | Literature Signal | Trial Signal | Evidence Strength |",
        "|---|---|---|---|---|---|",
    ]
    for _, r in top10.iterrows():
        lines.append(
            f"| {int(r['gap_rank'])} | {r['approved_symbol']} | "
            f"{r['gap_interpretation_tier']} | {r['literature_signal_label']} | "
            f"{r['trial_signal_label']} | {r['evidence_strength_label']} |"
        )
    lines.append("")

    lines += [
        "---\n",
        "## Validation Results\n",
    ]
    if validation_errors:
        lines.append(f"**{len(validation_errors)} validation issue(s) detected:**\n")
        for e in validation_errors:
            lines.append(f"- {e}")
    else:
        lines.append("All cards passed forbidden-phrase validation checks.")
    lines.append("")

    lines += [
        "---\n",
        "## Streamlit Integration Status\n",
        "- `Data/processed/target_evidence_cards.csv` is ready for dashboard loading.",
        "- `outputs/evidence_cards/*.md` are available for download buttons.",
        "- A new **Evidence Cards** dashboard page has been added to `app.py`.",
        "- The **Target Explorer** page now includes an evidence card download button.",
        "",
        "---\n",
        "## Limitations\n",
        "- All cards are computationally derived from a corpus sample.",
        "- Cards are not a substitute for expert biomedical review.",
        "- Symbol ambiguity and alias coverage are not fully resolved.",
        "- This is not clinical decision support.",
        "",
        "---\n",
        "*Generated by NeuroGraph Agent — Step 9: Evidence Card Generator*",
    ]

    out_path = REPORTS_DIR / "evidence_card_generation_summary.md"
    out_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"  [REPORT] Saved {out_path.name}")


# ── Main ──────────────────────────────────────────────────────────────────────

def main() -> None:
    print("\n=== NeuroGraph Agent: Step 9 — Evidence Card Generator ===\n")

    # Load data
    print("[1/7] Loading data files...")
    gap          = _load_csv(DATA / "research_gap_scores.csv",              "gap scores")
    kg_edges     = _load_csv(DATA / "knowledge_graph_edges.csv",            "graph edges")
    lit_assign   = _load_csv(DATA / "literature_topic_assignments.csv",     "lit assignments")
    trial_assign = _load_csv(DATA / "clinical_trial_topic_assignments.csv", "trial assignments")
    lit_clean    = _load_csv(DATA / "literature_clean.csv",                 "lit clean")
    _load_csv(DATA / "clinical_trials_clean.csv",                           "trials clean")
    _load_csv(DATA / "target_evidence_clean.csv",                           "target evidence")

    if gap is None:
        print("[ERROR] research_gap_scores.csv is required. Exiting.")
        return

    strong_syms = gap[
        gap["gap_interpretation_tier"] == "Strong text-supported gap signal"
    ]["approved_symbol"].tolist()

    print(f"  Loaded {len(gap)} targets, {len(strong_syms)} strong gap candidates.")

    # Generate cards for all targets
    print("\n[2/7] Generating evidence cards for all targets...")
    card_rows        = []
    validation_errors: list[str] = []
    n_created        = 0

    for i, (_, row) in enumerate(gap.iterrows(), 1):
        sym    = _safe(row.get("approved_symbol"))
        papers = get_matched_papers(sym, kg_edges, lit_assign, lit_clean)
        trials = get_matched_trials(sym, kg_edges, trial_assign)

        assoc_score = row.get("association_score", 0.0)
        lit_ment    = int(row.get("literature_mentions",          0) or 0)
        tri_ment    = int(row.get("trial_mentions",               0) or 0)

        md_text  = write_markdown_card(row, papers, trials)
        card_fn  = EVIDENCE_DIR / f"{sym}_evidence_card.md"
        card_fn.write_text(md_text, encoding="utf-8")
        n_created += 1

        errs = validate_card(card_fn, sym)
        validation_errors.extend(errs)

        card_rows.append({
            "approved_symbol":             sym,
            "approved_name":               _safe(row.get("approved_name")),
            "target_id":                   _safe(row.get("target_id")),
            "biotype":                     _safe(row.get("biotype")),
            "association_score":           assoc_score,
            "evidence_strength_label":     classify_evidence_strength(assoc_score),
            "gap_score":                   row.get("gap_score"),
            "conservative_gap_score":      row.get("conservative_gap_score"),
            "gap_rank":                    row.get("gap_rank"),
            "gap_category":                _safe(row.get("gap_category")),
            "gap_interpretation_tier":     _safe(row.get("gap_interpretation_tier")),
            "symbol_ambiguity_flag":       _safe(row.get("symbol_ambiguity_flag")),
            "literature_mentions":         lit_ment,
            "literature_documents_mentioned": int(row.get("literature_documents_mentioned", 0) or 0),
            "literature_signal_label":     classify_literature_signal(lit_ment),
            "trial_mentions":              tri_ment,
            "trial_documents_mentioned":   int(row.get("trial_documents_mentioned", 0) or 0),
            "trial_signal_label":          classify_trial_signal(tri_ment),
            "dominant_literature_theme":   infer_dominant_theme(papers, "topic_label"),
            "dominant_trial_theme":        infer_dominant_theme(trials, "topic_label"),
            "n_matched_papers":            len(papers),
            "n_matched_trials":            len(trials),
            "why_interesting":             generate_why_interesting(row),
            "key_limitations":             " | ".join(generate_limitations(row)),
            "suggested_next_steps":        " | ".join(generate_next_steps(row)),
            "evidence_card_path":          str(card_fn.relative_to(ROOT)),
        })

        if i % 100 == 0:
            print(f"  {i}/{len(gap)} cards written...")

    print(f"  Done. {n_created} cards created.")

    # Save CSV
    print("\n[3/7] Saving evidence card table...")
    cards_df = pd.DataFrame(card_rows)
    csv_path = DATA / "target_evidence_cards.csv"
    cards_df.to_csv(csv_path, index=False)
    print(f"  Saved {csv_path.name} ({len(cards_df)} rows, {len(cards_df.columns)} columns)")

    # Top brief pack
    print("\n[4/7] Building top gap candidate brief pack...")
    brief_md   = build_brief_pack(gap, kg_edges, lit_assign, lit_clean, trial_assign)
    brief_path = REPORTS_DIR / "top_gap_candidate_briefs.md"
    brief_path.write_text(brief_md, encoding="utf-8")
    print(f"  Saved {brief_path.name}")

    # Figure
    print("\n[5/7] Generating signal profile figure...")
    try:
        plot_signal_profile(gap, strong_syms)
    except Exception as exc:
        print(f"  [WARNING] Figure generation failed: {exc}")

    # Summary report
    print("\n[6/7] Writing summary report...")
    write_summary_report(gap, cards_df, n_created, validation_errors)

    # Validation summary
    print("\n[7/7] Validation checks...")
    assert len(cards_df) == len(gap), f"Row count mismatch: {len(cards_df)} vs {len(gap)}"
    assert cards_df["evidence_card_path"].notna().all(), "Some targets missing card path"
    md_files = list(EVIDENCE_DIR.glob("*.md"))
    assert len(md_files) == n_created, f"File count mismatch: {len(md_files)} vs {n_created}"
    strong_cards = cards_df[cards_df["gap_interpretation_tier"] == "Strong text-supported gap signal"]
    assert (strong_cards["why_interesting"].str.len() > 10).all(), "Some strong candidates missing why_interesting"
    if validation_errors:
        print(f"  [WARNING] {len(validation_errors)} forbidden-phrase issue(s) found:")
        for e in validation_errors:
            print(f"    {e}")
    else:
        print("  All cards passed forbidden-phrase checks.")
    print("  All structural validation checks passed.")

    # Final summary
    print("\n" + "=" * 60)
    print("STEP 9 COMPLETE")
    print("=" * 60)
    print(f"  Evidence cards created:   {n_created}")
    print(f"  Cards directory:          outputs/evidence_cards/")
    print(f"  Evidence card table:      Data/processed/target_evidence_cards.csv")
    print(f"  Top brief pack:           outputs/reports/top_gap_candidate_briefs.md")
    print(f"  Summary report:           outputs/reports/evidence_card_generation_summary.md")
    print(f"  Signal profile figure:    outputs/figures/cards_01_signal_profile_examples.png")
    print(f"\n  Strong gap candidates:    {len(strong_syms)}")
    print(f"  Top 5 by gap rank:")
    top5 = gap[gap["gap_interpretation_tier"] == "Strong text-supported gap signal"] \
               .sort_values("gap_rank").head(5)
    for _, r in top5.iterrows():
        print(f"    #{int(r['gap_rank'])}: {r['approved_symbol']}"
              f"  (lit={int(r['literature_mentions'])}, trial={int(r['trial_mentions'])})")
    print()


if __name__ == "__main__":
    main()
